# Generated by Django 4.1.2 on 2023-04-10 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_name_task_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='desctiption',
            new_name='description',
        ),
    ]
